print('welcome to the band new generator project!')
name=input('what is your native place or city you grow up?')
pname=input('what is your pet name?')
print('your band name could be='+name+' '+pname)
# (, and + both signs are used to join two senteces words are letters)
